name: Bump Tag Version

on:
  push:
    branches:
      - master

jobs:
  bump_tag:
    uses: jalavosus/workflows/.github/workflows/bump_tag.yml@v1.5.1
    secrets:
      token: ${{ secrets.TAG_PAT }}