name: Release

on:
  push:
    tags:
      - "v[01].[0-9]+.[0-9]+"

jobs:
  release:
    uses: jalavosus/workflows/.github/workflows/go-release-archive.yml@v1.5.1
    with:
      package-name: hdwallet-go
      archive-files: "*.go go.mod go.sum LICENSE"
    secrets:
      gpg-secret-key: ${{ secrets.GPG_SECRET_KEY }}
      gpg-password:   ${{ secrets.GPG_PASSWORD }}