name: Test

on:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  test:
    uses: jalavosus/workflows/.github/workflows/go-test-117_compat.yml@v1.2.0
    with:
      run_cmd: "go test ./..."
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}